services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pki-2fa
    ports:
      - "8080:8080"

    volumes:
      # Named volumes
      - seed-data:/data
      - cron-output:/cron

      # Key files
      - ./student_private.pem:/app/student_private.pem:ro
      - ./student_public.pem:/app/student_public.pem:ro
      - ./instructor_public.pem:/app/instructor_public.pem:ro

      # External folders
      - ./data:/data
      - ./cron:/cron

    environment:
      TZ: UTC

    restart: unless-stopped

volumes:
  seed-data:
  cron-output:
